# Simple Redis Service for Development (No Persistent Storage)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-data-collection
  namespace: crypto-collectors
  labels:
    app: redis-data-collection
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-data-collection
  template:
    metadata:
      labels:
        app: redis-data-collection
        component: database
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          ports:
            - containerPort: 6379
              name: redis
          args:
            - redis-server
            - --maxmemory
            - "256mb"
            - --maxmemory-policy
            - "allkeys-lru"
            - --protected-mode
            - "no"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: redis-data-collection
  namespace: crypto-collectors
  labels:
    app: redis-data-collection
    component: database
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: redis-data-collection
  type: ClusterIP
