apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: crypto-data-collection
  labels:
    app: alertmanager
    component: monitoring
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'localhost:587'
      smtp_from: 'alerts@crypto-data-collection.local'

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'web.hook'
      routes:
        - match:
            severity: critical
          receiver: 'critical-alerts'
        - match:
            severity: warning
          receiver: 'warning-alerts'

    receivers:
      - name: 'web.hook'
        webhook_configs:
          - url: 'http://localhost:5001/'
            send_resolved: true

      - name: 'critical-alerts'
        email_configs:
          - to: 'oncall@crypto-data-collection.local'
            subject: 'CRITICAL: {{ .GroupLabels.alertname }}'
            body: |
              {{ range .Alerts }}
              Alert: {{ .Annotations.summary }}
              Description: {{ .Annotations.description }}
              {{ end }}

      - name: 'warning-alerts'
        email_configs:
          - to: 'team@crypto-data-collection.local'
            subject: 'WARNING: {{ .GroupLabels.alertname }}'
            body: |
              {{ range .Alerts }}
              Alert: {{ .Annotations.summary }}
              Description: {{ .Annotations.description }}
              {{ end }}
