apiVersion: batch/v1
kind: Job
metadata:
  name: enhanced-materialized-test
  namespace: crypto-collectors
spec:
  template:
    spec:
      tolerations:
      - key: "data-platform"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: materialized-updater
        image: aitest-materialized-updater:enhanced
        imagePullPolicy: Never
        command: ["python", "materialized_updater_enhanced.py", "2", "insert-only"]
        env:
        - name: DB_HOST
          value: "host.docker.internal"
        - name: DB_USER
          value: "news_collector"
        - name: DB_PASSWORD
          value: "99Rules!"
        - name: DB_NAME
          value: "crypto_prices"
      restartPolicy: Never
  backoffLimit: 3