apiVersion: apps/v1
kind: Deployment
metadata:
  name: enhanced-crypto-prices
  namespace: crypto-collectors
  labels:
    app: enhanced-crypto-prices
    app.kubernetes.io/name: enhanced-crypto-prices
    app.kubernetes.io/part-of: crypto-ai-system
    component: data-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enhanced-crypto-prices
  template:
    metadata:
      labels:
        app: enhanced-crypto-prices
        component: data-collector
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: solution-area
                operator: In
                values:
                - data-platform
      tolerations:
      - effect: NoSchedule
        key: data-platform
        operator: Equal
        value: "true"
      containers:
      - name: enhanced-crypto-prices
        image: enhanced-crypto-prices:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: MYSQL_HOST
          value: "192.168.230.162"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "news_collector"
        - name: MYSQL_PASSWORD
          value: "99Rules!"
        - name: MYSQL_DATABASE
          value: "crypto_prices"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: CRYPTO_PRICES_TABLE
          value: "price_data_real"
        - name: HIGH_COLUMN
          value: "high_24h"
        - name: LOW_COLUMN
          value: "low_24h"
        - name: OPEN_COLUMN
          value: "open_24h"
        - name: VOLUME_COLUMN
          value: "volume_usd_24h"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 45
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 800m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: enhanced-crypto-prices
  namespace: crypto-collectors
  labels:
    app: enhanced-crypto-prices
spec:
  selector:
    app: enhanced-crypto-prices
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP