apiVersion: batch/v1
kind: Job
metadata:
  name: enhanced-crypto-prices-manual-fix
  namespace: crypto-collectors
spec:
  template:
    spec:
      containers:
      - name: price-collector
        image: enhanced-crypto-prices:price-fix-working
        imagePullPolicy: Never
        env:
        - name: MYSQL_HOST
          value: "host.docker.internal"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: crypto-db-secrets
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: crypto-db-secrets
              key: password
        - name: MYSQL_DATABASE
          value: "crypto_prices"
        command: ["/bin/sh"]
        args: ["-c", "python main.py &  sleep 10 && curl -X POST http://localhost:8000/collect"]
      restartPolicy: Never
  backoffLimit: 3