apiVersion: batch/v1
kind: CronJob
metadata:
  name: enhanced-crypto-price-collector-fixed
  namespace: crypto-collectors
spec:
  schedule: "*/15 * * * *"  # Every 15 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: price-collector-fixed
            image: enhanced-crypto-prices:price-fix-working
            imagePullPolicy: Never
            env:
            - name: MYSQL_HOST
              value: "host.docker.internal"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: crypto-db-secrets
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crypto-db-secrets
                  key: password
            - name: MYSQL_DATABASE
              value: "crypto_prices"
            command: ["/bin/sh"]
            args: ["-c", "python main.py & sleep 15 && curl -X POST http://localhost:8000/collect && sleep 5"]
          restartPolicy: OnFailure
      backoffLimit: 3