apiVersion: v1
kind: Service
metadata:
  name: enhanced-crypto-prices
  namespace: crypto-collectors
  labels:
    app: enhanced-crypto-prices
spec:
  selector:
    app: enhanced-crypto-prices
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP