apiVersion: batch/v1
kind: CronJob
metadata:
  name: materialized-updater-cron
  namespace: crypto-collectors
  labels:
    app: materialized-updater-cron
    component: ml-service
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: materialized-updater-cron
            component: ml-service
        spec:
          restartPolicy: OnFailure
          tolerations:
          - effect: NoSchedule
            key: data-platform
            operator: Equal
            value: "true"
          - effect: NoSchedule
            key: analytics-infrastructure
            operator: Equal
            value: "true"
          - effect: NoSchedule
            key: trading-engine
            operator: Equal
            value: "true"
          containers:
          - name: materialized-updater
            image: aitest-materialized-updater:mysql-fix-v3
            imagePullPolicy: Never
            command:
            - python
            - materialized_updater_fixed.py
            - --interval
            - "2"
            - --update-if-changed
            env:
            - name: MYSQL_HOST
              value: host.docker.internal
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: crypto-db-secrets
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crypto-db-secrets
                  key: password
            - name: MYSQL_DATABASE
              value: crypto_prices
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 1Gi