---
# LLM Integration Client Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-integration-client
  namespace: crypto-collectors
  labels:
    app: llm-integration-client
    component: data-enhancement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-integration-client
  template:
    metadata:
      labels:
        app: llm-integration-client
        component: data-enhancement
    spec:
      containers:
      - name: llm-integration-client
        image: llm-integration-client:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8040
          name: http
        env:
        - name: AITEST_OLLAMA_ENDPOINT
          value: "http://ollama-llm-service.crypto-trading.svc.cluster.local:8050"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8040
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8040
          initialDelaySeconds: 10
          periodSeconds: 10
      restartPolicy: Always
---
# LLM Integration Client Service
apiVersion: v1
kind: Service
metadata:
  name: llm-integration-client
  namespace: crypto-collectors
  labels:
    app: llm-integration-client
spec:
  type: ClusterIP
  ports:
  - port: 8040
    targetPort: 8040
    protocol: TCP
    name: http
  selector:
    app: llm-integration-client
---
# Enhanced Sentiment Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enhanced-sentiment
  namespace: crypto-collectors
  labels:
    app: enhanced-sentiment
    component: data-enhancement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enhanced-sentiment
  template:
    metadata:
      labels:
        app: enhanced-sentiment
        component: data-enhancement
    spec:
      containers:
      - name: enhanced-sentiment
        image: enhanced-sentiment:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8038
          name: http
        env:
        - name: LLM_CLIENT_ENDPOINT
          value: "http://llm-integration-client.crypto-collectors.svc.cluster.local:8040"
        - name: CRYPTOBERT_ENDPOINT
          value: "http://cryptobert.crypto-collectors.svc.cluster.local:8000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8038
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8038
          initialDelaySeconds: 10
          periodSeconds: 10
      restartPolicy: Always
---
# Enhanced Sentiment Service
apiVersion: v1
kind: Service
metadata:
  name: enhanced-sentiment
  namespace: crypto-collectors
  labels:
    app: enhanced-sentiment
spec:
  type: ClusterIP
  ports:
  - port: 8038
    targetPort: 8038
    protocol: TCP
    name: http
  selector:
    app: enhanced-sentiment
---
# Narrative Analyzer Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: narrative-analyzer
  namespace: crypto-collectors
  labels:
    app: narrative-analyzer
    component: data-enhancement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: narrative-analyzer
  template:
    metadata:
      labels:
        app: narrative-analyzer
        component: data-enhancement
    spec:
      containers:
      - name: narrative-analyzer
        image: narrative-analyzer:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8039
          name: http
        env:
        - name: LLM_CLIENT_ENDPOINT
          value: "http://llm-integration-client.crypto-collectors.svc.cluster.local:8040"
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: crypto-data-secrets
              key: mysql-host
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: crypto-data-secrets
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: crypto-data-secrets
              key: mysql-password
        - name: MYSQL_DATABASE
          value: "crypto_news"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8039
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8039
          initialDelaySeconds: 10
          periodSeconds: 10
      restartPolicy: Always
---
# Narrative Analyzer Service
apiVersion: v1
kind: Service
metadata:
  name: narrative-analyzer
  namespace: crypto-collectors
  labels:
    app: narrative-analyzer
spec:
  type: ClusterIP
  ports:
  - port: 8039
    targetPort: 8039
    protocol: TCP
    name: http
  selector:
    app: narrative-analyzer