apiVersion: batch/v1
kind: Job
metadata:
  name: manual-ml-ohlc-backfill-v2
  namespace: crypto-collectors
spec:
  template:
    spec:
      restartPolicy: OnFailure
      tolerations:
      - key: "data-platform"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: ml-backfill
        image: aitest-materialized-updater:mysql-fix-v2
        command: ["python", "materialized_updater_fixed.py", "--interval", "1", "--update-if-changed"]
        env:
        - name: MYSQL_HOST
          value: host.docker.internal
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: crypto-db-secrets
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: crypto-db-secrets
              key: password
        - name: MYSQL_DATABASE
          value: crypto_prices
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"