apiVersion: batch/v1
kind: Job
metadata:
  name: materialized-updater-test
  namespace: crypto-collectors
spec:
  template:
    spec:
      restartPolicy: Never
      nodeSelector:
        solution-area: data-platform
      tolerations:
      - effect: NoSchedule
        key: data-platform
        operator: Equal
        value: "true"
      containers:
      - name: materialized-updater
        image: aitest-materialized-updater:dxy-fix
        imagePullPolicy: Never
        command: ["python", "-c", "print('Materialized updater test successful'); import mysql.connector; print('MySQL connector available')"]
        env:
        - name: MYSQL_HOST
          value: "192.168.230.162"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: crypto-db-secrets
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: crypto-db-secrets
        - name: MYSQL_DATABASE
          value: "crypto_prices"