apiVersion: apps/v1
kind: Deployment
metadata:
  name: materialized-updater
  namespace: crypto-collectors
  labels:
    app: materialized-updater
    component: ml-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: materialized-updater
  template:
    metadata:
      labels:
        app: materialized-updater
        component: ml-service
    spec:
      containers:
      - name: materialized-updater
        image: aitest-materialized-updater:dxy-fix
        imagePullPolicy: Never
        command: ["python", "materialized_updater_fixed.py", "--continuous", "--interval", "5"]
        env:
        - name: MYSQL_HOST
          value: "192.168.230.162"
        - name: MYSQL_USER
          value: "news_collector"
        - name: MYSQL_PASSWORD
          value: "99Rules!"
        - name: MYSQL_DATABASE
          value: "crypto_prices"
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import mysql.connector; mysql.connector.connect(host='192.168.230.162', user='news_collector', password='99Rules!', database='crypto_prices').close()"
          initialDelaySeconds: 60
          periodSeconds: 300
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - "import mysql.connector; mysql.connector.connect(host='192.168.230.162', user='news_collector', password='99Rules!', database='crypto_prices').close()"
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
      restartPolicy: Always