apiVersion: batch/v1
kind: CronJob
metadata:
  name: materialized-updater-cron-fixed
  namespace: crypto-collectors
  labels:
    app: materialized-updater-cron
    component: ml-service
spec:
  schedule: "*/30 * * * *"  # Changed to 30 minutes instead of 15
  concurrencyPolicy: Forbid  # CRITICAL: Prevent overlapping jobs
  successfulJobsHistoryLimit: 1  # Keep only 1 successful job
  failedJobsHistoryLimit: 1      # Keep only 1 failed job
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1800  # 30 minute timeout
      template:
        metadata:
          labels:
            app: materialized-updater-cron
            component: ml-service
        spec:
          restartPolicy: OnFailure
          tolerations:
          - key: "data-platform"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
          containers:
          - name: materialized-updater
            image: aitest-materialized-updater:mysql-fix-v3
            imagePullPolicy: Never
            command: ["python", "materialized_updater_fixed.py", "--interval", "1", "--update-if-changed"]
            env:
            - name: MYSQL_HOST
              value: host.docker.internal
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: crypto-db-secrets
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crypto-db-secrets
                  key: password
            - name: MYSQL_DATABASE
              value: crypto_prices
            resources:
              requests:
                memory: "512Mi"
                cpu: "250m"
              limits:
                memory: "1Gi"
                cpu: "500m"