apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-cleanup-sa
  namespace: crypto-collectors

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: crypto-collectors
  name: pod-cleanup-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-cleanup-binding
  namespace: crypto-collectors
subjects:
- kind: ServiceAccount
  name: pod-cleanup-sa
  namespace: crypto-collectors
roleRef:
  kind: Role
  name: pod-cleanup-role
  apiGroup: rbac.authorization.k8s.io