apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-monitor
  namespace: crypto-collectors
  labels:
    app: service-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-monitor
  template:
    metadata:
      labels:
        app: service-monitor
    spec:
      containers:
      - name: monitor
        image: curlimages/curl:latest
        command: ["/bin/sh"]
        args:
        - -c
        - |
          while true; do
            echo "🔍 $(date): Checking service health..."
            
            # Check each core service individually (no bash arrays in /bin/sh)
            echo "Checking enhanced-crypto-prices..."
            if curl -sf http://enhanced-crypto-prices.crypto-collectors.svc.cluster.local:8001/health >/dev/null 2>&1; then
              echo "✅ enhanced-crypto-prices: healthy"
            else
              echo "❌ enhanced-crypto-prices: unhealthy"
            fi
            
            echo "Checking crypto-news-collector..."
            if curl -sf http://crypto-news-collector.crypto-collectors.svc.cluster.local:8000/health >/dev/null 2>&1; then
              echo "✅ crypto-news-collector: healthy"
            else
              echo "❌ crypto-news-collector: unhealthy"
            fi
            
            echo "Checking stock-sentiment-collector..."
            if curl -sf http://stock-sentiment-collector.crypto-collectors.svc.cluster.local:8000/health >/dev/null 2>&1; then
              echo "✅ stock-sentiment-collector: healthy"
            else
              echo "❌ stock-sentiment-collector: unhealthy"
            fi
            
            echo "Checking technical-indicators..."
            if curl -sf http://technical-indicators.crypto-collectors.svc.cluster.local:8000/health >/dev/null 2>&1; then
              echo "✅ technical-indicators: healthy"
            else
              echo "❌ technical-indicators: unhealthy"
            fi
            
            echo "Health check cycle complete. Sleeping for 5 minutes..."
            # Sleep for 5 minutes
            sleep 300
          done
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
      nodeSelector:
        solution-area: data-platform
      tolerations:
      - effect: NoSchedule
        key: data-platform
        operator: Equal
        value: "true"