apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api-gateway
  namespace: crypto-collectors
  labels:
    app: simple-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-api-gateway
  template:
    metadata:
      labels:
        app: simple-api-gateway
    spec:
      containers:
        - name: api-gateway
          image: crypto-data-api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_HOST
              value: "192.168.230.162"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: "news_collector"
            - name: MYSQL_PASSWORD
              value: "99Rules!"
            - name: MYSQL_DATABASE
              value: "crypto_prices"
            - name: PORT
              value: "8000"
            - name: WORKERS
              value: "2"
            - name: API_KEY_MASTER
              value: "master-crypto-data-key-2025"
            - name: API_KEY_TRADING
              value: "trading-crypto-data-key-2025"
            - name: API_KEY_READONLY
              value: "readonly-crypto-data-key-2025"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: simple-api-gateway
  namespace: crypto-collectors
spec:
  selector:
    app: simple-api-gateway
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: simple-api-gateway-external
  namespace: crypto-collectors
spec:
  selector:
    app: simple-api-gateway
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
  type: LoadBalancer
