apiVersion: batch/v1
kind: Job
metadata:
  name: test-enhanced-crypto-prices
  namespace: crypto-data-collection
spec:
  template:
    spec:
      containers:
      - name: enhanced-crypto-prices
        image: enhanced-crypto-prices:latest
        imagePullPolicy: Never
        env:
        - name: MYSQL_HOST
          value: "crypto-mysql-service.crypto-data-collection.svc.cluster.local"
        - name: MYSQL_USER
          value: "crypto_user"
        - name: MYSQL_PASSWORD
          value: "crypto_password_2024"
        - name: MYSQL_DATABASE
          value: "crypto_prices"
        - name: COINGECKO_API_KEY
          value: "CG-94NCcVD2euxaGTZe94bS2oYz"
        command: ["python", "main.py"]
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      restartPolicy: Never
  backoffLimit: 3