apiVersion: batch/v1
kind: Job
metadata:
  name: test-enhanced-crypto-collection
  namespace: crypto-collectors
spec:
  template:
    spec:
      tolerations:
      - effect: NoSchedule
        key: data-platform
        operator: Equal
        value: "true"
      - effect: NoSchedule
        key: analytics-infrastructure
        operator: Equal
        value: "true"
      - effect: NoSchedule
        key: trading-engine
        operator: Equal
        value: "true"
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      containers:
      - name: test
        image: curlimages/curl:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - |
          echo "Triggering enhanced crypto prices collection with API key..."
          response=$(curl -s -w "%{http_code}" -X POST http://enhanced-crypto-prices.crypto-collectors.svc.cluster.local:8001/collect -d '{"symbols": ["BTC", "ETH", "ADA"], "force_update": true}' -H "Content-Type: application/json")
          http_code=$(echo "$response" | tail -c 4)
          body=$(echo "$response" | head -c -4)
          
          echo "HTTP Status: $http_code"
          echo "Response: $body"
          
          if [ "$http_code" = "200" ]; then
            echo "✅ Enhanced crypto prices collection successful"
          else
            echo "❌ Enhanced crypto prices collection failed"
          fi
      restartPolicy: Never
  backoffLimit: 1