apiVersion: batch/v1
kind: Job
metadata:
  name: test-volume-collection
  namespace: crypto-collectors
spec:
  template:
    spec:
      containers:
      - name: test-volume
        image: curlimages/curl:latest
        command: ["curl"]
        args: ["-X", "POST", "http://enhanced-crypto-prices.crypto-collectors.svc.cluster.local:8000/collect"]
      restartPolicy: Never
      nodeSelector:
        solution-area: data-platform
      tolerations:
      - effect: NoSchedule
        key: data-platform
        operator: Equal
        value: "true"
  backoffLimit: 1