apiVersion: v1
kind: Pod
metadata:
  name: test-schema-fix
  namespace: crypto-collectors
spec:
  tolerations:
  - effect: NoSchedule
    key: data-platform
    operator: Equal
    value: "true"
  containers:
  - name: enhanced-crypto-prices
    image: enhanced-crypto-prices:schema-fix
    imagePullPolicy: Never
    env:
    - name: MYSQL_HOST
      value: host.docker.internal
    - name: MYSQL_USER
      value: news_collector
    - name: MYSQL_PASSWORD
      value: 99Rules!
    - name: MYSQL_DATABASE
      value: crypto_prices
    - name: CRYPTO_PRICES_TABLE
      value: price_data_real
    - name: CLOSE_COLUMN
      value: current_price
    - name: OPEN_COLUMN
      value: open_24h
    - name: HIGH_COLUMN
      value: high_24h
    - name: LOW_COLUMN
      value: low_24h
    - name: VOLUME_COLUMN
      value: volume_usd_24h
    - name: COINGECKO_API_KEY
      value: "CG-94NCcVD2euxaGTZe94bS2oYz"
    command: ["python", "-c", "
import json
import requests
import time

# Wait for service to start
time.sleep(2)

# Test the collect endpoint
response = requests.post('http://localhost:8000/collect')
result = response.json()

print('=== SCHEMA FIX TEST RESULTS ===')
print(f'Status: {result.get(\"status\")}')
print(f'Symbols collected: {result.get(\"symbols_successful\")}/{result.get(\"symbols_requested\")}')
print(f'Stored to MySQL: {result.get(\"stored_to_mysql\")}')
print(f'Processing time: {result.get(\"processing_time_ms\")}ms')

if result.get('stored_to_mysql', 0) > 0:
    print('✅ SCHEMA FIX SUCCESSFUL - Data is being stored!')
else:
    print('❌ SCHEMA FIX FAILED - Data not being stored')
    
print('\\nFull response:')
print(json.dumps(result, indent=2))
"]
  restartPolicy: Never
  nodeSelector:
    solution-area: data-platform