apiVersion: batch/v1
kind: Job
metadata:
  name: test-technical-indicators-fixed
  namespace: crypto-collectors
spec:
  template:
    spec:
      tolerations:
      - effect: NoSchedule
        key: data-platform
        operator: Equal
        value: "true"
      - effect: NoSchedule
        key: analytics-infrastructure
        operator: Equal
        value: "true"
      - effect: NoSchedule
        key: trading-engine
        operator: Equal
        value: "true"
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      containers:
      - name: test
        image: curlimages/curl:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - |
          echo "Testing technical indicators collection after database fix..."
          response=$(curl -s -w "%{http_code}" -X POST http://technical-indicators.crypto-collectors.svc.cluster.local:8000/collect)
          http_code=$(echo "$response" | tail -c 4)
          body=$(echo "$response" | head -c -4)
          
          echo "HTTP Status: $http_code"
          echo "Response: $body"
          
          if [ "$http_code" = "200" ]; then
            echo "✅ Technical indicators collection successful"
          else
            echo "❌ Technical indicators collection failed"
          fi
      restartPolicy: Never
  backoffLimit: 1