apiVersion: batch/v1
kind: Job
metadata:
  name: trigger-macro-economic
  namespace: crypto-collectors
spec:
  template:
    spec:
      tolerations:
      - effect: NoSchedule
        key: data-platform
        operator: Equal
        value: "true"
      - effect: NoSchedule
        key: analytics-infrastructure
        operator: Equal
        value: "true"
      - effect: NoSchedule
        key: trading-engine
        operator: Equal
        value: "true"
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      containers:
      - name: trigger
        image: curlimages/curl:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - |
          echo "Triggering macro economic data collection..."
          response=$(curl -s -w "%{http_code}" -X POST http://macro-economic.crypto-collectors.svc.cluster.local:8000/collect/realtime)
          http_code=$(echo "$response" | tail -c 4)
          body=$(echo "$response" | head -c -4)
          
          echo "HTTP Status: $http_code"
          echo "Response: $body"
          
          if [ "$http_code" = "200" ]; then
            echo "✅ Macro economic collection successful"
          else
            echo "❌ Macro economic collection failed"
            exit 1
          fi
      restartPolicy: Never
  backoffLimit: 1