apiVersion: apps/v1
kind: Deployment
metadata:
  name: unified-ohlc-collector
  namespace: crypto-collectors
spec:
  template:
    spec:
      containers:
      - name: unified-ohlc-collector
        env:
        - name: DATABASE_HOST
          value: "host.docker.internal"
        - name: DATABASE_USER
          value: "root"
        - name: DATABASE_PASSWORD
          value: "99Rules!"
        - name: DATABASE_NAME
          value: "crypto_prices"
        - name: OHLC_TABLE
          value: "ohlc_data"
        - name: ENABLE_OHLC_COLLECTION
          value: "true"