apiVersion: v1
kind: Pod
metadata:
  name: verify-backfill
  namespace: crypto-collectors
spec:
  restartPolicy: Never
  containers:
  - name: verify
    image: python:3.11-slim
    env:
    - name: MYSQL_HOST
      value: "host.docker.internal"
    - name: MYSQL_USER
      value: "news_collector"
    - name: MYSQL_PASSWORD
      value: "99Rules!"
    - name: MYSQL_DATABASE
      value: "crypto_news"
    command: ["sh", "-c"]
    args:
    - |
      pip install mysql-connector-python
      python << 'EOF'
      import mysql.connector
      import os
      
      conn = mysql.connector.connect(
          host=os.environ['MYSQL_HOST'],
          user=os.environ['MYSQL_USER'],
          password=os.environ['MYSQL_PASSWORD'],
          database=os.environ['MYSQL_DATABASE']
      )
      
      cursor = conn.cursor()
      
      cursor.execute("SELECT COUNT(*) FROM social_sentiment_data")
      total_records = cursor.fetchone()[0]
      print(f"Total sentiment records: {total_records}")
      
      cursor.execute("SELECT COUNT(*) FROM social_sentiment_data WHERE collection_source = 'backfill_job'")
      backfilled_records = cursor.fetchone()[0]
      print(f"Backfilled records: {backfilled_records}")
      
      cursor.execute("SELECT DATE(timestamp) as date, COUNT(*) as count FROM social_sentiment_data GROUP BY DATE(timestamp) ORDER BY date DESC LIMIT 15")
      recent_data = cursor.fetchall()
      print("Recent data by date:")
      for row in recent_data:
          print(f"  {row[0]}: {row[1]} records")
      
      cursor.close()
      conn.close()
      EOF