apiVersion: v1
kind: Service
metadata:
  name: enhanced-macro-collector-service
  namespace: crypto-data-collection
  labels:
    app: enhanced-macro-collector
spec:
  selector:
    app: enhanced-macro-collector
  ports:
    - name: http
      port: 8003
      targetPort: 8003
      protocol: TCP
  type: ClusterIP