apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-news-collector
  namespace: crypto-data-collection
  labels:
    app: crypto-news-collector
    component: data-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-news-collector
  template:
    metadata:
      labels:
        app: crypto-news-collector
        component: data-collector
    spec:
      nodeSelector:
        node-type: data-collection # Target the data collection node
      containers:
        - name: crypto-news-collector
          image: python:3.11-slim
          command: ["/bin/bash", "-c"]
          args:
            - "pip install fastapi uvicorn requests && python /app/services/news-collection/crypto_news_collector.py"
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: centralized-db-config
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: centralized-db-config
                  key: MYSQL_PORT
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: centralized-db-secrets
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: centralized-db-secrets
                  key: mysql-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: centralized-db-config
                  key: MYSQL_DATABASE
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: app-code
              mountPath: /app
      volumes:
        - name: app-code
          hostPath:
            path: E:\git\crypto-data-collection # Mount the entire project directory
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-news-collector
  namespace: crypto-data-collection
  labels:
    app: crypto-news-collector
    component: data-collector
spec:
  selector:
    app: crypto-news-collector
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
