apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-collector
  namespace: crypto-data-collection
  labels:
    app: sentiment-collector
    component: data-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-collector
  template:
    metadata:
      labels:
        app: sentiment-collector
        component: data-collector
    spec:
      nodeSelector:
        node-type: data-collection # Target the data collection node
      containers:
        - name: sentiment-collector
          image: python:3.11-slim
          command: ["/bin/bash", "-c"]
          args:
            - "pip install fastapi uvicorn torch transformers requests && python /app/backend/services/sentiment/sentiment.py"
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: centralized-db-config
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: centralized-db-config
                  key: MYSQL_PORT
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: centralized-db-secrets
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: centralized-db-secrets
                  key: mysql-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: centralized-db-config
                  key: MYSQL_DATABASE
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi
          volumeMounts:
            - name: app-code
              mountPath: /app
      volumes:
        - name: app-code
          hostPath:
            path: /e/git/crypto-data-collection # Mount the entire project directory
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-collector
  namespace: crypto-data-collection
  labels:
    app: sentiment-collector
    component: data-collector
spec:
  selector:
    app: sentiment-collector
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
