# Dedicated Data Collection Namespace and Resources
apiVersion: v1
kind: Namespace
metadata:
  name: crypto-data-collection
  labels:
    purpose: data-collection
    isolation: dedicated
    system: crypto-trading
    component: data-collection-node
---
# Resource quota for data collection workloads
apiVersion: v1
kind: ResourceQuota
metadata:
  name: data-collection-quota
  namespace: crypto-data-collection
spec:
  hard:
    requests.cpu: "12"
    requests.memory: 24Gi
    limits.cpu: "24"
    limits.memory: 48Gi
    persistentvolumeclaims: "20"
    services: "30"
    secrets: "10"
    configmaps: "10"
---
# Limit ranges for individual pods
apiVersion: v1
kind: LimitRange
metadata:
  name: data-collection-limits
  namespace: crypto-data-collection
spec:
  limits:
  - default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "500m"
      memory: "1Gi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim