# Configuration for Data Collection Services
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-collection-config
  namespace: crypto-collectors
data:
  # Database Configuration - Use Existing Windows Databases (External)
  MYSQL_HOST: "192.168.230.162"  # External Windows MySQL IP
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "crypto_prices"
  MYSQL_USER: "news_collector"
  
  # Redis Configuration - Internal Kubernetes Service
  REDIS_HOST: "redis-data-collection.crypto-collectors.svc.cluster.local"
  REDIS_PORT: "6379"
  
  # Internal Service DNS Names
  API_GATEWAY_URL: "simple-api-gateway.crypto-collectors.svc.cluster.local:8000"
  ENHANCED_CRYPTO_PRICES_URL: "enhanced-crypto-prices.crypto-collectors.svc.cluster.local:8000"
  NEWS_COLLECTOR_URL: "crypto-news-collector.crypto-collectors.svc.cluster.local:8000"
  SENTIMENT_COLLECTOR_URL: "simple-sentiment-collector.crypto-collectors.svc.cluster.local:8000"
  MATERIALIZED_UPDATER_URL: "materialized-updater.crypto-collectors.svc.cluster.local:8000"
  # Trading Database Configuration
  TRADING_MYSQL_DATABASE: "crypto_transactions"
  STOCK_MYSQL_DATABASE: "stock_market_news"
  
  # Collection Intervals
  PRICE_COLLECTION_INTERVAL: "300"  # 5 minutes
  NEWS_COLLECTION_INTERVAL: "900"   # 15 minutes
  SENTIMENT_COLLECTION_INTERVAL: "900"  # 15 minutes
  TECHNICAL_COLLECTION_INTERVAL: "300"  # 5 minutes
  SOCIAL_COLLECTION_INTERVAL: "1800"    # 30 minutes
  MACRO_COLLECTION_INTERVAL: "3600"     # 1 hour
  
  # Data Quality Settings
  DATA_VALIDATION_ENABLED: "true"
  MAX_RETRY_ATTEMPTS: "3"
  ERROR_THRESHOLD_PERCENT: "5"
  
  # API Configuration
  API_RATE_LIMIT: "1000"  # requests per minute
  API_TIMEOUT: "30"       # seconds
  
  # Collection Sources
  COINGECKO_PREMIUM_ENABLED: "true"
  FRED_API_ENABLED: "true"
  GUARDIAN_API_ENABLED: "true"
  REDDIT_API_ENABLED: "true"
  
  # Storage Configuration
  S3_BUCKET: "crypto-data-archives"
  BACKUP_RETENTION_DAYS: "90"
  ARCHIVE_COMPRESSION: "gzip"
---
# Logging Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-config
  namespace: crypto-collectors
data:
  log_level: "INFO"
  log_format: "json"
  log_output: "stdout"
  enable_debug: "false"
---
# API Gateway Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: crypto-collectors
data:
  # API Gateway Settings
  PORT: "8000"
  WORKERS: "4"
  MAX_CONNECTIONS: "1000"
  KEEPALIVE_TIMEOUT: "65"
  
  # CORS Settings
  CORS_ORIGINS: "http://localhost:3000,https://crypto-trading-dashboard.local"
  CORS_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_HEADERS: "Content-Type,Authorization,X-API-Key"
  
  # Rate Limiting
  RATE_LIMIT_REQUESTS: "100"
  RATE_LIMIT_WINDOW: "60"
  
  # Authentication
  AUTH_REQUIRED: "true"
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRY: "86400"  # 24 hours
---
# Monitoring Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: crypto-collectors
data:
  # Prometheus Settings
  PROMETHEUS_PORT: "9090"
  METRICS_PATH: "/metrics"
  SCRAPE_INTERVAL: "15s"
  
  # Grafana Settings
  GRAFANA_PORT: "3000"
  GRAFANA_ADMIN_USER: "admin"
  
  # Alert Thresholds
  CPU_ALERT_THRESHOLD: "80"
  MEMORY_ALERT_THRESHOLD: "85"
  DISK_ALERT_THRESHOLD: "90"
  COLLECTION_FAILURE_THRESHOLD: "3"